services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: akineko
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: akineko_db_local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: